
package pe.com.claro.analitics.first.coberturaws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import pe.com.claro.analitics.first.coberturaws.types.CoberturaRequest;
import pe.com.claro.analitics.first.coberturaws.types.CoberturaResponse;
import pe.com.claro.analitics.first.coberturaws.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CoberturaWSPortType", targetNamespace = "http://claro.com.pe/analitics/first/CoberturaWS/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CoberturaWSPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns pe.com.claro.analitics.first.coberturaws.types.CoberturaResponse
     */
    @WebMethod(action = "http://claro.com.pe/analitics/first/CoberturaWS/validarCobertura")
    @WebResult(name = "CoberturaResponse", targetNamespace = "http://claro.com.pe/analitics/first/CoberturaWS/types", partName = "parameters")
    public CoberturaResponse validarCobertura(
        @WebParam(name = "CoberturaRequest", targetNamespace = "http://claro.com.pe/analitics/first/CoberturaWS/types", partName = "parameters")
        CoberturaRequest parameters);

}
