
package pe.com.claro.analitics.first.coberturaws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CoberturaService", targetNamespace = "http://claro.com.pe/analitics/first/CoberturaWS/", wsdlLocation = "file:/C:/WorkSpace_Eclipse/Weblogic12c_capacitacion/CoberturaWS/src/CoberturaWS.wsdl")
public class CoberturaService
    extends Service
{

    private final static URL COBERTURASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(pe.com.claro.analitics.first.coberturaws.CoberturaService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = pe.com.claro.analitics.first.coberturaws.CoberturaService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/WorkSpace_Eclipse/Weblogic12c_capacitacion/CoberturaWS/src/CoberturaWS.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/WorkSpace_Eclipse/Weblogic12c_capacitacion/CoberturaWS/src/CoberturaWS.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        COBERTURASERVICE_WSDL_LOCATION = url;
    }

    public CoberturaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CoberturaService() {
        super(COBERTURASERVICE_WSDL_LOCATION, new QName("http://claro.com.pe/analitics/first/CoberturaWS/", "CoberturaService"));
    }

    /**
     * 
     * @return
     *     returns CoberturaWSPortType
     */
    @WebEndpoint(name = "CoberturaWSPort")
    public CoberturaWSPortType getCoberturaWSPort() {
        return super.getPort(new QName("http://claro.com.pe/analitics/first/CoberturaWS/", "CoberturaWSPort"), CoberturaWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CoberturaWSPortType
     */
    @WebEndpoint(name = "CoberturaWSPort")
    public CoberturaWSPortType getCoberturaWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://claro.com.pe/analitics/first/CoberturaWS/", "CoberturaWSPort"), CoberturaWSPortType.class, features);
    }

}
